version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://booksdb_uiiu_user:gpqwL1UEWW5WcrZIMFskpAN4qLQ0a1i3@dpg-crhph45umphs73c73u20-a.oregon-postgres.render.com/booksdb_uiiu

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://booksdb_uiiu_user:gpqwL1UEWW5WcrZIMFskpAN4qLQ0a1i3@dpg-crhph45umphs73c73u20-a.oregon-postgres.render.com/booksdb_uiiu
